# Site settings
title: "Kevin Lacker's blog"
# email: lacker at gmail
description: > # this means to ignore newlines until "baseurl:"
  TODO: update blog description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lacker.io" # the base hostname & protocol for your site
twitter_username: lacker
github_username:  lacker

# Build settings
markdown: kramdown
